{
 "title": "Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debugging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "cn-monitor-1.cn.ece.ntua.gr:9093"
   },
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance versions and up time",
   "type": "table",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"} * on (instance, cluster) group_left process_start_time_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(alertmanager_build_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "stat",
   "description": "Number of peers in the Alertmanager cluster.",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_cluster_members{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "stat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active alerts in $instance",
     "type": "timeseries",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{instance=~\"$instance\"}) by (state)",
       "legendFormat": "Alerts: State: {{state}}"
      }
     ]
    },
    {
     "title": "Received alerts by status for $instance",
     "type": "timeseries",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts_received_total{instance=~\"$instance\"}) by (status)",
       "legendFormat": "Alerts: Status: {{status}}"
      }
     ]
    },
    {
     "title": "Invalid received alerts",
     "type": "timeseries",
     "description": "The total number of received alerts that were invalid.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "alertmanager_alerts_invalid_total{instance=~\"$instance\"}",
       "legendFormat": "Invalid alerts: "
      }
     ]
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifications sent from $instance",
     "type": "timeseries",
     "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_notifications_total{instance=~\"$instance\"}) by (integration)",
       "legendFormat": "Total: Integration: {{integration}}"
      },
      {
       "expr": "sum(alertmanager_notifications_failed_total{instance=~\"$instance\"}) by (integration)",
       "legendFormat": "Failed: Integration: {{ integration }}"
      }
     ]
    },
    {
     "title": "Notification durations per integration on $instance",
     "type": "timeseries",
     "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum((alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"})) by (integration)",
       "legendFormat": "Latency: Integration: {{integration}}"
      },
      {
       "expr": "sum(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}) by (integration)",
       "legendFormat": "Latency: Integration: {{integration}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusterhealth score for $instance",
     "type": "timeseries",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_health_score{instance=~\"$instance\"}",
       "legendFormat": "Cluster health score:"
      }
     ]
    },
    {
     "title": "Cluster members count on $instance",
     "type": "timeseries",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red color.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_members{instance=~\"$instance\"}",
       "legendFormat": "Number of cluster members:"
      },
      {
       "expr": "alertmanager_cluster_failed_peers{instance=~\"$instance\"}",
       "legendFormat": "Number of failed peers:"
      }
     ]
    },
    {
     "title": "Cluster peers left/joined on $instance",
     "type": "timeseries",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_cluster_peers_left_total{instance=~\"$instance\"})",
       "legendFormat": "Cluster joined peers:"
      },
      {
       "expr": "sum(alertmanager_cluster_peers_joined_total{instance=~\"$instance\"})",
       "legendFormat": "Cluster left peers:"
      }
     ]
    },
    {
     "title": "Cluster reconnections on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "sum(alertmanager_cluster_reconnections_total{instance=~\"$instance\"})",
       "legendFormat": "Sucessful reconnections: "
      },
      {
       "expr": "sum(alertmanager_cluster_reconnections_failed_total{instance=~\"$instance\"})",
       "legendFormat": "Failed reconnections:"
      }
     ]
    },
    {
     "title": "Cluster messages count on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_cluster_messages_sent_total{instance=~\"$instance\"}) by (msg_type)",
       "legendFormat": "Messages sent: Message type: {{msg_type}}"
      },
      {
       "expr": "sum(alertmanager_cluster_messages_received_total{instance=~\"$instance\"}) by (msg_type)",
       "legendFormat": "Messages received: Message type: {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages size on $instance",
     "type": "timeseries",
     "description": "On positive axis is size of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(alertmanager_cluster_messages_sent_size_total{instance=~\"$instance\"}) by (msg_type)",
       "legendFormat": "Messages sent size: {{msg_type}}"
      },
      {
       "expr": "sum(alertmanager_cluster_messages_received_size_total{instance=~\"$instance\"}) by (msg_type)",
       "legendFormat": "Messages received size: {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages queue on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_messages_pruned_total{instance=~\"$instance\"}",
       "legendFormat": "Pruned messaged:"
      },
      {
       "expr": "alertmanager_cluster_messages_queued{instance=~\"$instance\"}",
       "legendFormat": "Queued messages:"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of oversized gossip messages on $instance",
     "type": "timeseries",
     "description": "Gossip messages dropped: Number of oversized gossip messages that were dropped due to a full message queue.\n\nGossip messages failed: Number of oversized gossip message sends that failed.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_oversized_gossip_message_dropped_total{instance=~\"$instance\"})",
       "legendFormat": "Gossip messages dropped: {{key}}"
      },
      {
       "expr": "sum(alertmanager_oversized_gossip_message_failure_total{instance=~\"$instance\"})",
       "legendFormat": "Gossip messages failed: {{key}}"
      }
     ]
    },
    {
     "title": "Duration of oversized gossip messages on $instance",
     "type": "timeseries",
     "description": "Duration of oversized gossip message requests.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(alertmanager_oversize_gossip_message_duration_seconds_bucket{instance=~\"$instance\"})",
       "legendFormat": " Duration:"
      }
     ]
    },
    {
     "title": "Number of  propagated gossip messages on $instance",
     "type": "timeseries",
     "description": "Silent gossip messages propagated: Number of received gossip messages that have been further gossiped.\n\nNflog gossip messages propagated: Number of received gossip messages that have been further gossiped.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "sum(alertmanager_silences_gossip_messages_propagated_total{instance=~\"$instance\"})",
       "legendFormat": "Silent gossip messages propagated:"
      },
      {
       "expr": "sum(alertmanager_nflog_gossip_messages_propagated_total{instance=~\"$instance\"})",
       "legendFormat": "Nflog gossip messages propagated:"
      }
     ]
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nf log queries count for $instance",
     "type": "timeseries",
     "description": "Nf log query count: Number of notification log queries were received.\n\nNf log query errors: Number notification log received queries that failed.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "sum(alertmanager_nflog_queries_total{instance=~\"$instance\"})",
       "legendFormat": "Nf log query count:"
      },
      {
       "expr": "sum(alertmanager_nflog_query_errors_total{instance=~\"$instance\"})",
       "legendFormat": "Nf log query errors:"
      }
     ]
    },
    {
     "title": "Nf log query duration for $instance",
     "type": "timeseries",
     "description": "Duration of notification log query evaluation.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$instance\"})",
       "legendFormat": "Nf log query duration:"
      }
     ]
    },
    {
     "title": "Nf log snapshot size for $instance",
     "type": "timeseries",
     "description": "Size of the last notification log snapshot in bytes.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Nf log snapshot size:"
      }
     ]
    },
    {
     "title": "Nf log snapshot duration for $instance",
     "type": "timeseries",
     "description": "Duration of the last notification log snapshot.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$instance\"})",
       "legendFormat": "Nf log snapshot size:"
      }
     ]
    },
    {
     "title": "Nf log Go GC time for $instance",
     "type": "timeseries",
     "description": "Duration of the last notification log garbage collection cycle.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "alertmanager_nflog_gc_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "Cluster joined peers: Quantile: {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Silences count by state on $instance",
     "type": "timeseries",
     "description": "Number of silences by state.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_silences{instance=~\"$instance\"}",
       "legendFormat": "Silences: {{state}}"
      }
     ]
    },
    {
     "title": "Silences query count on $instance",
     "type": "timeseries",
     "description": "Silences query count: Number of silence queries were received.\n\nSilecnces query fails: Number of silence received queries did not succeed.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_silences_queries_total{instance=~\"$instance\"})",
       "legendFormat": "Silecnces query count:"
      },
      {
       "expr": "sum(alertmanager_silences_query_errors_total{instance=~\"$instance\"})",
       "legendFormat": "Silecnces query fails:"
      }
     ]
    },
    {
     "title": "Silences query duration on $instance",
     "type": "timeseries",
     "description": "Duration of silence query evaluation.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$instance\"})",
       "legendFormat": "Silecnces query duration:"
      }
     ]
    },
    {
     "title": "Silences snapshot size on $instance",
     "type": "timeseries",
     "description": "Size of the last silence snapshot in bytes.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Silecnces snapshot size:"
      }
     ]
    },
    {
     "title": "Silences snapshot duration on $instance",
     "type": "timeseries",
     "description": "Duration of the last silence snapshot.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_duration_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "Silecnces snapshot duration:"
      }
     ]
    },
    {
     "title": "Silences GC duraton on $instance",
     "type": "timeseries",
     "description": "Duration of the last silence garbage collection cycle.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "alertmanager_silences_gc_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "Silecnces GC  duration:"
      }
     ]
    }
   ]
  }
 ]
}