{
 "title": "BBB Exporter",
 "tags": [
  "BigBlueButton",
  "prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "host",
    "query": {
     "query": "label_values(bbb_api_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "High level stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB Host",
   "type": "stat",
   "description": "Host of BigBlueButton.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbb_meetings{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BBB API",
   "type": "stat",
   "description": "Boolean value which indicates if API is responding. The result 1 (true) designates successful API response.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "BigBlueButton Exporter Version",
   "type": "stat",
   "description": "BigBlueButton Exporter version.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bbb_exporter{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "description": "Start time of the process since unix epoch in seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "Start  time:"
    }
   ]
  },
  { "title": "Participants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Max participants",
   "type": "stat",
   "description": "Maximum number of participants within the last week and since start of system.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(bbb_meetings_participants{instance=\"$instance\"}[1w])",
     "legendFormat": "Since 1 week"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{instance=\"$instance\"}[100y])",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "Type of participants",
   "type": "timeseries",
   "description": "Total participants: Total number of participants in all BigBlueButton meetings.\n\nListeners: Total number of listeners in all BigBlueButton meetings.\n\nVoice participants: Total number of voice participants in all BigBlueButton meetings.\n\nVideo participants: Total number of video participants in all BigBlueButton meetings.",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Total participants: "
    },
    {
     "expr": "bbb_meetings_listeners{instance=\"$instance\"}",
     "legendFormat": "Listeners participants:"
    },
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice participants:"
    },
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Video participants:"
    }
   ]
  },
  {
   "title": "Participants by Client Type",
   "type": "timeseries",
   "description": "Total number of participants in all BigBlueButton meetings by client.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bbb_meetings_participant_clients{instance=\"$instance\"}",
     "legendFormat": "Participants: Type: {{type}}"
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recordings",
     "type": "stat",
     "description": "Processing: Total number of BigBlueButton recordings processing.\n\nPublished: Total number of BigBlueButton recordings published.\n\nUnpublished: Total number of BigBlueButton recordings unpublished.\n\nDeleted: Total number of BigBlueButton recordings deleted.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "bbb_recordings_processing{instance=\"$instance\"}",
       "legendFormat": "Processing"
      },
      {
       "expr": "bbb_recordings_unprocessed{instance=\"$instance\"}",
       "legendFormat": "Unprocessed"
      },
      {
       "expr": "bbb_recordings_published{instance=\"$instance\"}",
       "legendFormat": "Published"
      },
      {
       "expr": "bbb_recordings_unpublished{instance=\"$instance\"}",
       "legendFormat": "Unpublished"
      },
      {
       "expr": "bbb_recordings_deleted{instance=\"$instance\"}",
       "legendFormat": "Deleted"
      }
     ]
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Rooms",
     "type": "timeseries",
     "description": "Number of meeting rooms.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bbb_room_participants_gcount{instance=\"$instance\"}",
       "legendFormat": "Rooms:"
      }
     ]
    }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heatmap of Room Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "bbb_room_participants_bucket{instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Video Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "bbb_room_video_participants_bucket{instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Voice Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "bbb_room_voice_participants_bucket{instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heatmap of Listeners Participants",
     "type": "heatmap",
     "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "bbb_room_listeners_bucket{instance=\"$instance\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter Metrics Response Time (95th Percentile)",
     "type": "timeseries",
     "description": "BigBlueButton API call latency.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket[5m])) by (le, endpoint, parameters))",
       "legendFormat": "Latency: Endpoint: {{endpoint}} Parameters: {{parameters}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Time spent:"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual memory size",
     "type": "timeseries",
     "description": "Virtual memory size in bytes.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Virtual memory size:"
      }
     ]
    },
    {
     "title": "Resident memory",
     "type": "timeseries",
     "description": "Resident memory size in bytes.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Resident memory size:"
      }
     ]
    }
   ]
  },
  {
   "title": "Python stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python implementation",
     "type": "stat",
     "description": "Python implementation.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "python_info{instance=~\"$instance\"}",
       "legendFormat": "{{implementation}} "
      }
     ]
    },
    {
     "title": "Python major version",
     "type": "stat",
     "description": "Python major version.",
     "gridPos": { "h": 6, "w": 4, "x": 5, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "python_info{instance=~\"$instance\"}",
       "legendFormat": "{{major}}"
      }
     ]
    },
    {
     "title": "Python minor version",
     "type": "stat",
     "description": "Python minor version.",
     "gridPos": { "h": 6, "w": 4, "x": 9, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "python_info{instance=~\"$instance\"}",
       "legendFormat": "{{minor}}"
      }
     ]
    },
    {
     "title": "Python version",
     "type": "stat",
     "description": "Python version.",
     "gridPos": { "h": 6, "w": 5, "x": 13, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "python_info{instance=~\"$instance\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Python patchlevel",
     "type": "stat",
     "description": "Python patchlevel.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "python_info{instance=~\"$instance\"}",
       "legendFormat": "{{patchlevel}}"
      }
     ]
    },
    {
     "title": "Python garbage collector collections",
     "type": "timeseries",
     "description": "Number of times each generation was collected.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "python_gc_collections_total{instance=~\"$instance\"}",
       "legendFormat": "Collections: Generation: {{generation}}"
      }
     ]
    },
    {
     "title": "Python garbage collector objects",
     "type": "timeseries",
     "description": "Collected: Objects collected during garbage collection.\n\nUncollectable: Uncollectable object found during garbage collection.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "python_gc_objects_collected_total{instance=~\"$instance\"}",
       "legendFormat": "Collected objects: Generation: {{generation}}"
      },
      {
       "expr": "python_gc_objects_uncollectable_total{instance=~\"$instance\"}",
       "legendFormat": "Uncollectable objects: Generation: {{generation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "description": "File descriptors: Number of open file descriptors.\n\nMaximum file descriptors: Maximum number of open file descriptors.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$instance\"}",
       "legendFormat": "File descriptors:"
      },
      {
       "expr": "process_max_fds{instance=~\"$instance\"}",
       "legendFormat": "Maximum file descriptors:"
      }
     ]
    }
   ]
  }
 ]
}