{
 "title": "Blackbox Exporter",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "site",
    "query": "https://helios.ntua.gr, https://courses.cn.ntua.gr, https://www.ece.ntua.gr, https://www.cn.ntua.gr, https://students.ece.ntua.gr, http://users.ntua.gr, http://onos.telecom.ece.ntua.gr, https://cn-monitor-1.cn.ece.ntua.gr:3000, http://cn-monitor-1.cn.ece.ntua.gr:9090,  https://bbb2.cn.ntua.gr,  https://bbb.cn.ntua.gr"
   }
  ]
 },
 "panels": [
  { "title": "High level stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Target",
   "type": "stat",
   "description": "Target of probing.",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "description": "Indication whether the IP protocol is IPv4 or IPv6. The value 4 designates the IPv4 protocol and the value 6 the IPv6 protocol.",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ip_protocol{instance=~\"$instance\"}",
     "legendFormat": "IP version"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "description": "Version of HTTP.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$instance\"}",
     "legendFormat": "Version"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "description": "Response HTTP status code.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SSL",
   "type": "stat",
   "description": "Indicates if SSL was used for the final redirect.",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "stat",
   "description": "Earliest SSL cert expiry.",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$instance\"}-time()"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP request duration by phase",
     "type": "timeseries",
     "description": "Duration of HTTP request by phase, summed over all redirects.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "Duration: Phase: {{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redirects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP redirects",
     "type": "timeseries",
     "description": "The number of HTTP redirects.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "probe_http_redirects{instance=~\"$instance\"}",
       "legendFormat": "Redirects:"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP probing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Probe success (boolean)",
     "type": "timeseries",
     "description": "Boolean value which indicates if the probe was a success. The result 1 (true) designates successful probe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "probe_success{instance=~\"$instance\"}",
       "legendFormat": "Probe success:"
      }
     ]
    },
    {
     "title": "Probe failure due to regex",
     "type": "timeseries",
     "description": "Boolean value which indicates if the probe failed due to regex. The result 1 (true) designates unsuccessful probe due to regex.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "probe_failed_due_to_regex{instance=~\"$instance\"}",
       "legendFormat": "Probe regex failure:"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "timeseries",
     "description": "Duration in seconds of the probe completion.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "Duration:"
      }
     ]
    },
    {
     "title": "HTTP content response length",
     "type": "timeseries",
     "description": "Length of HTTP content response.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "probe_http_content_length{instance=~\"$instance\"}",
       "legendFormat": "Length:"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Lookup",
     "type": "timeseries",
     "description": "Duration in seconds of the completion of the DNS Lookup.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_dns_lookup_time_seconds{instance=~\"$instance\"}",
       "legendFormat": "Duration:"
      }
     ]
    }
   ]
  }
 ]
}