{
 "title": "Gitlab-Monitor",
 "description": "Monitor Gitlab: Memory, Process-Age, Sidekiq queue/Latency, Process Count",
 "tags": [ "gitlab" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"gitlab_exporter_metrics\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gitlab Host",
   "type": "stat",
   "description": "Host of Gitlab.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sidekiq_jobs_processed_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Sidekiq workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq workers",
     "type": "timeseries",
     "description": "Number of sidekiq workers",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sidekiq_workers_size{instance=~\"$instance\"}",
       "legendFormat": "Workers:"
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq processes",
     "type": "timeseries",
     "description": "Sidekiq processes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sidekiq_processes_size{instance=~\"$instance\"}",
       "legendFormat": "Processes:"
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq queue size",
     "type": "timeseries",
     "description": "Sidekiq queue size by name.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sidekiq_queue_size{instance=~\"$instance\"}",
       "legendFormat": "Name: {{name}}"
      }
     ]
    },
    {
     "title": "Default sidekiq queue latency",
     "type": "timeseries",
     "description": "Default sidekiq queue latency in seconds.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sidekiq_default_queue_latency_seconds{instance=~\"$instance\"}",
       "legendFormat": "Latency:"
      }
     ]
    },
    {
     "title": "Sidekiq queue latency",
     "type": "timeseries",
     "description": "Sidekiq queue latency by name in seconds.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sidekiq_queue_latency_seconds{instance=~\"$instance\"}",
       "legendFormat": "Name: {{name}}"
      }
     ]
    },
    {
     "title": "Sidekiq queue paused",
     "type": "timeseries",
     "description": "Paused sidekiq queue size by name.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sidekiq_queue_paused{instance=~\"$instance\"}",
       "legendFormat": "Name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total sidekiq jobs processed",
     "type": "timeseries",
     "description": "Number of total proccessed sidekiq jobs.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sidekiq_jobs_processed_total{instance=~\"$instance\"}",
       "legendFormat": "Jobs:"
      }
     ]
    },
    {
     "title": "Dead sidekiq jobs",
     "type": "timeseries",
     "description": "Number of dead sidekiq jobs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sidekiq_jobs_dead_size{instance=~\"$instance\"}",
       "legendFormat": "Jobs:"
      }
     ]
    },
    {
     "title": "Retry sidekiq jobs",
     "type": "timeseries",
     "description": "Number of retry sidekiq jobs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sidekiq_jobs_retry_size{instance=~\"$instance\"}",
       "legendFormat": "Jobs:"
      }
     ]
    },
    {
     "title": "Scheduled sidekiq jobs",
     "type": "timeseries",
     "description": "Number of scheduled sidekiq jobs.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sidekiq_jobs_scheduled_size{instance=~\"$instance\"}",
       "legendFormat": "Jobs:"
      }
     ]
    },
    {
     "title": "Enqueued sidekiq jobs",
     "type": "timeseries",
     "description": "Number of enqueued sidekiq jobs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sidekiq_jobs_enqueued_size{instance=~\"$instance\"}",
       "legendFormat": "Jobs:"
      }
     ]
    },
    {
     "title": "Sidekiq total jobs failed",
     "type": "timeseries",
     "description": "Number of total sidekiq jobs that have been  failed.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sidekiq_jobs_failed_total{instance=~\"$instance\"}",
       "legendFormat": "Jobs: Host: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitlab database rows",
     "type": "timeseries",
     "description": "Number of Gitlab database rows by name.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gitlab_database_rows{instance=~\"$instance\", query_name!=\"users\"}",
       "legendFormat": "Database rows: Name: {{query_name}}"
      },
      {
       "expr": "gitlab_database_rows{instance=~\"$instance\", query_name=~\"users\"}",
       "legendFormat": "Database rows: Name: {{query_name}} Admin: {{admin}} External: {{external}} State: {{state}} Access level: {{access_level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ci",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ci unarchived traces",
     "type": "timeseries",
     "description": "Number of Ci unarchived traces.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "ci_unarchived_traces{instance=~\"$instance\"}",
       "legendFormat": "Traces:"
      }
     ]
    },
    {
     "title": "Ci stale builds",
     "type": "timeseries",
     "description": "Number of Ci stale builds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "ci_stale_builds{instance=~\"$instance\"}",
       "legendFormat": "Builds:"
      }
     ]
    }
   ]
  },
  {
   "title": "Ruby garbage collector memory allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ruby garbage collector memory allocation increase ",
     "type": "timeseries",
     "description": "Number of Ruby garbage collector memory allocation increase in bytes.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ruby_gc_stat_malloc_increase_bytes{instance=~\"$instance\"}",
       "legendFormat": "Memory allocation increase:"
      },
      {
       "expr": "ruby_gc_stat_malloc_increase_bytes_limit{instance=~\"$instance\"}",
       "legendFormat": "Memory allocation increase limit:"
      }
     ]
    },
    {
     "title": "Old Ruby garbage collector memory allocation",
     "type": "timeseries",
     "description": "Old memory allocation increase: Number of old garbage collector memory allocation increase in bytes.\n\nOld memory allocation increase limit: Number of old garbage collector memory allocation increase bytes limit.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ruby_gc_stat_oldmalloc_increase_bytes{instance=~\"$instance\"}",
       "legendFormat": "Old memory allocation increase:"
      },
      {
       "expr": "ruby_gc_stat_oldmalloc_increase_bytes_limit{instance=~\"$instance\"}",
       "legendFormat": "Old memory allocation increase limit:"
      }
     ]
    }
   ]
  },
  {
   "title": "Ruby garbage collector heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sorted Ruby garbage collection heap length",
     "type": "timeseries",
     "description": "Length of Sorted Ruby garbage collection heap.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ruby_gc_stat_heap_sorted_length{instance=~\"$instance\"}",
       "legendFormat": "Length:"
      }
     ]
    },
    {
     "title": "Ruby garbage collector heap slots",
     "type": "timeseries",
     "description": "Available slots: Number of available Ruby garbage collector heap slots.\n\nLive slots: Number of live Ruby garbage collector heap slots.\n\nMarked slots: Number of marked Ruby garbage collector heap slots.\n\nFree slots: Number of free Ruby garbage collector heap slots.\n\nFinal slots: Number of final Ruby garbage collector heap slots.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ruby_gc_stat_heap_available_slots{instance=~\"$instance\"}",
       "legendFormat": "Available slots:"
      },
      {
       "expr": "ruby_gc_stat_heap_live_slots{instance=~\"$instance\"}",
       "legendFormat": "Live slots:"
      },
      {
       "expr": "ruby_gc_stat_heap_marked_slots{instance=~\"$instance\"}",
       "legendFormat": "Marked slots:"
      },
      {
       "expr": "ruby_gc_stat_heap_free_slots{instance=~\"$instance\"}",
       "legendFormat": "Free slots:"
      },
      {
       "expr": "ruby_gc_stat_heap_final_slots{instance=~\"$instance\"}",
       "legendFormat": "Final slots:"
      }
     ]
    },
    {
     "title": "Allocatable Ruby garbage collector heap pages",
     "type": "timeseries",
     "description": "Number of allocatable Ruby garbage collector pages.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "ruby_gc_stat_heap_allocatable_pages{instance=~\"$instance\"}",
       "legendFormat": "Allocatable pages:"
      },
      {
       "expr": "ruby_gc_stat_heap_allocated_pages{instance=~\"$instance\"}",
       "legendFormat": "Allocated pages:"
      },
      {
       "expr": "ruby_gc_stat_total_allocated_pages{instance=~\"$instance\"}",
       "legendFormat": "Total allocated pages:"
      },
      {
       "expr": "ruby_gc_stat_heap_eden_pages{instance=~\"$instance\"}",
       "legendFormat": "Eden pages:"
      },
      {
       "expr": "ruby_gc_stat_total_freed_pages{instance=~\"$instance\"}",
       "legendFormat": "Total freed pages:"
      },
      {
       "expr": "ruby_gc_stat_heap_tomb_pages{instance=~\"$instance\"}",
       "legendFormat": "Tomb pages:"
      }
     ]
    }
   ]
  },
  {
   "title": "Ruby garbage collector objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ruby objetcs",
     "type": "timeseries",
     "description": "Allocated objects: Number of total allocated Ruby garbage collector objects.\n\nFreed objects: Number of freed Ruby garbage collector objects.\n\nUnprotected wb objects: Number of unprotected wb Ruby garbage collector objects.\n\nUnprotected wb objects limit: Limit of unprotected wb Ruby garbage collector objects.\n\nOld objects: Number of old Ruby garbage collector objects.\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ruby_gc_stat_total_allocated_objects{instance=~\"$instance\"}",
       "legendFormat": "Allocated objects:"
      },
      {
       "expr": "ruby_gc_stat_total_freed_objects{instance=~\"$instance\"}",
       "legendFormat": "Freed objects:"
      },
      {
       "expr": "ruby_gc_stat_remembered_wb_unprotected_objects{instance=~\"$instance\"}",
       "legendFormat": "Unprotected wb objects:"
      },
      {
       "expr": "ruby_gc_stat_remembered_wb_unprotected_objects_limit{instance=~\"$instance\"}",
       "legendFormat": "Unprotected wb objects imit:"
      },
      {
       "expr": "ruby_gc_stat_old_objects{instance=~\"$instance\"}",
       "legendFormat": "Old objects:"
      }
     ]
    }
   ]
  },
  {
   "title": "Ruby garbage collector size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ruby garbage collection size",
     "type": "timeseries",
     "description": "Count: Count of Ruby garbage collection size.\n\nMinor count: Minor count of Ruby garbage collection size.\n\nMajor count: Major count of Ruby garbage collection size.\n\nCompact count: Compact count of Ruby garbage collection size.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ruby_gc_stat_count{instance=~\"$instance\"}",
       "legendFormat": "Count:"
      },
      {
       "expr": "ruby_gc_stat_minor_gc_count{instance=~\"$instance\"}",
       "legendFormat": "Minor count:"
      },
      {
       "expr": "ruby_gc_stat_major_gc_count{instance=~\"$instance\"}",
       "legendFormat": "Major count:"
      },
      {
       "expr": "ruby_gc_stat_compact_count{instance=~\"$instance\"}",
       "legendFormat": "Compact count:"
      }
     ]
    }
   ]
  }
 ]
}