{
 "title": "Host stats",
 "description": "Uses prometheus queries via pryorda/vmware_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "host",
    "query": "vmware_vcenter, vmware_vcenter2"
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(vmware_vm_power_state, vm_name)"
    }
   },
   { "name": "dc_name", "label": "dc_name", "query": { "query": "label_values(dc_name)" } },
   { "name": "datastore", "label": "ds_name", "query": { "query": "label_values(ds_name)" } }
  ]
 },
 "panels": [
  { "title": "High level stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host name",
   "type": "stat",
   "description": "Name of Ηost.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "vmware_host_hardware_info{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"} ",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Server model",
   "type": "stat",
   "description": "Server model.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}) ",
     "legendFormat": "{{hardware_model}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Host product version.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "description": "Build number.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_product_info{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
     "legendFormat": "{{build}}"
    }
   ]
  },
  {
   "title": "Host In Maintenance (Boolean value)",
   "type": "stat",
   "description": "Boolean value which indicates if Host is in maintenance mode. The result 1 (true) designates maintenance mode.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_maintenance_mode{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}==1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "description": "Total count of Virtual Machines, regardless of power state.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Host uptime",
   "type": "stat",
   "description": "Uptime of Ηost.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(vmware_host_boot_timestamp_seconds{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"})"
    }
   ]
  },
  {
   "title": "Host connection state",
   "type": "stat",
   "description": "Host connection state (connected / disconnected / notResponding).",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_connection_state{job=~\"$job\", dc_name=\"$dc_name\"}",
     "legendFormat": "State: {{state}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power watt",
     "type": "timeseries",
     "description": "Host power use in Watt.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "vmware_host_sensor_power_watt{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Datacenter: {{ dc_name }} {{cluster_name}} Sensor name: {{name}}"
      }
     ]
    },
    {
     "title": "Electric Current",
     "type": "timeseries",
     "description": "Host electric current value in Ampere.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "vmware_host_sensor_power_current{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Datacenter: {{ dc_name }} {{cluster_name}} Sensor name: {{name}}"
      }
     ]
    },
    {
     "title": "Electric Voltage",
     "type": "timeseries",
     "description": "Host electric Voltage value in Volt.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "vmware_host_sensor_power_voltage{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Datacenter: {{ dc_name }} {{cluster_name}} Sensor name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Fan temperature",
     "type": "timeseries",
     "description": "VMWare Fan temperature in centigrade.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "vmware_host_sensor_temperature{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} Sensor name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Model",
     "type": "stat",
     "description": "CPU model.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_host_hardware_info{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "{{hardware_cpu_model}}"
      }
     ]
    },
    {
     "title": "CPUs",
     "type": "stat",
     "description": "Number of processors in the Host.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(vmware_host_num_cpu{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"})"
      }
     ]
    },
    {
     "title": "CPU Capacity",
     "type": "stat",
     "description": "Host CPU max availability in MHz.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vmware_host_cpu_max{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}) "
      }
     ]
    },
    {
     "title": "Host CPU utilization",
     "type": "timeseries",
     "description": "Usage: Actively used CPU of the host, as a percentage of the total available CPU. Active CPU is approximately equal to the ratio of the used CPU to the available CPU.\n\nDemand: The amount of CPU resources a virtual machine would use if there were no CPU contention or CPU limit.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(vmware_host_cpu_usagemhz_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}) * 100 / (vmware_host_cpu_max{job=~\"$job\",  dc_name=~\"$dc_name\", cluster_name=\"\"})",
       "legendFormat": "CPU Usage:  Datacenter: {{ dc_name }} "
      },
      {
       "expr": "((vmware_host_cpu_demand_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}) * 100) / (vmware_host_cpu_max{job=~\"$job\",  dc_name=~\"$dc_name\", cluster_name=\"\"})",
       "legendFormat": "CPU Demand: Datacenter: {{ dc_name }} "
      }
     ]
    },
    {
     "title": "Host CPU time utilization",
     "type": "bargauge",
     "description": "Ready: Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval. CPU ready time is dependent on the number of virtual machines on the host and their CPU loads.\n\nCo-stop: Time the virtual machine is ready to run, but is unable to run due to co-scheduling constraints.\n\nSwap wait: CPU time spent waiting for swap-in.\n\nIdle: Total time that the CPU spent in an idle state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_host_cpu_ready_summation{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "CPU Ready:  Datacenter: {{ dc_name }} "
      },
      {
       "expr": "(vmware_host_cpu_costop_summation{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}/200)",
       "legendFormat": "CPU Co-Stop:  Datacenter: {{ dc_name }} "
      },
      {
       "expr": "(vmware_host_cpu_swapwait_summation{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}/200)",
       "legendFormat": "CPU Swap Wait:  Datacenter: {{ dc_name }} "
      },
      {
       "expr": "vmware_host_cpu_idle_summation{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}/200",
       "legendFormat": "CPU Idle:  Datacenter: {{ dc_name }} "
      }
     ]
    },
    {
     "title": "Host CPU time used",
     "type": "timeseries",
     "description": "Time accounted to the virtual machine. If a system service runs on behalf of this virtual machine, the time spent by that service (represented by cpu.system) should be charged to this virtual machine. \nIf not, the time spent (represented by cpu.overlap) should not be charged against this virtual machine.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vmware_host_cpu_used_summation{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=~\"\"}",
       "legendFormat": "Time used:  Datacenter: {{ dc_name }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host memory capacity",
     "type": "stat",
     "description": "Host maximum memory availability in Mbytes.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_host_memory_max{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}"
      }
     ]
    },
    {
     "title": "Host memory usage",
     "type": "timeseries",
     "description": "Memory usage as percentage of total configured or available memory.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((vmware_host_memory_usage{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=~\"\"}) / (vmware_host_memory_max{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=~\"\"}))* 100",
       "legendFormat": "Memory usage: Datacenter: {{ dc_name }} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Host active memory",
     "type": "timeseries",
     "description": "Active: Amount of memory that is actively used, as estimated by VMkernel based on recently touched memory pages.\n\nSum of all active metrics for all powered-on virtual machines plus vSphere services (such as COS, vpxa) on the host.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "vmware_host_mem_active_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Active memory: Datacenter: {{ dc_name }} "
      }
     ]
    },
    {
     "title": "Memory Swap in",
     "type": "timeseries",
     "description": "Amount of memory swapped-in from Host cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "vmware_host_mem_swapin_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Swap in: Datacenter: {{ dc_name }} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Memory Swap in rate",
     "type": "timeseries",
     "description": "Rate at which memory is being swapped from Host cache into active memory.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_host_mem_swapinRate_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Swap in rate: Datacenter: {{ dc_name }} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Memory Swap out",
     "type": "timeseries",
     "description": "Amount of memory swapped-out to Host cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "vmware_host_mem_swapout_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Swap out: Datacenter: {{ dc_name }} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Memory Swap out rate",
     "type": "timeseries",
     "description": "Rate at which memory is being swapped from active memory to Host cache.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_host_mem_swapoutRate_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Swap out rate: Datacenter: {{ dc_name }} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Balloning",
     "type": "timeseries",
     "description": "Balloning: Amount of memory allocated by the virtual machine memory control driver (vmmemctl), which is installed with VMware Tools. It is a VMware exclusive memory-management driver that controls ballooning.\n\nThe sum of all vmmemctl values for all powered-on virtual machines, plus vSphere services on the host. If the balloon target value is greater than the balloon value, the VMkernel inflates the balloon, causing more virtual machine memory to be reclaimed. If the balloon target value is less than the balloon value, the VMkernel deflates the balloon, which allows the virtual machine to consume additional memory if needed.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "vmware_host_mem_vmmemctl_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Balloning: Datacenter: {{ dc_name }} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Average Host memory latency",
     "type": "gauge",
     "description": "Percentage of time the virtual machine is waiting to access swapped or compressed memory.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_host_mem_latency_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Latency: Datacenter: {{ dc_name }} {{cluster_name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Datastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datastore type",
     "type": "stat",
     "description": "Datastore type (VMFS, NetworkFileSystem, NetworkFileSystem41, CIFS, VFAT, VSAN, VFFS).",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_datastore_type{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}",
       "legendFormat": "Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} Datastore type: {{ds_type}} "
      }
     ]
    },
    {
     "title": "Datastore accessibility status (boolean)",
     "type": "timeseries",
     "description": "Boolean value which indicates if Datastore is accessible. The result 1 (true) designates successful accessibility.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "vmware_datastore_accessible{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}",
       "legendFormat": "Accessibility status: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}}"
      }
     ]
    },
    {
     "title": "Datastore maintenance mode (boolean)",
     "type": "timeseries",
     "description": "Boolean value which indicates if Datastore is in maintenance mode. The result 1 (true) designates maintenance mode.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "vmware_datastore_maintenance_mode{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}",
       "legendFormat": "Maintenance status: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Hosts using datastore",
     "type": "timeseries",
     "description": "Number of Hosts using each Datastore.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "vmware_datastore_hosts{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}",
       "legendFormat": "Hosts: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "VMs per datastore",
     "type": "timeseries",
     "description": "Number of Virtual Machines using each Datastore.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "vmware_datastore_vms{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}",
       "legendFormat": "VMs: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Datastore capacity size",
     "type": "timeseries",
     "description": "Datastore capacity size in bytes.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmware_datastore_capacity_size{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Capacity size: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Datastore free space",
     "type": "timeseries",
     "description": "Datastore free space size in bytes.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmware_datastore_freespace_size{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Capacity size: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Datastore uncommited size",
     "type": "timeseries",
     "description": "Datastore uncommitted size in bytes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmware_datastore_uncommited_size{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Uncommited size: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Datastore provisioned  size",
     "type": "timeseries",
     "description": "Provizioned size: Amount of storage set aside for use by a datastore or a virtual machineFiles on the datastore and the virtual machine can expand to this size, but not beyond it. Available from datastore and virtual machine target entities.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmware_datastore_provisoned_size{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}",
       "legendFormat": "Provisioned size: Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{cluster_name}} "
      }
     ]
    },
    {
     "title": "Used Datastore",
     "type": "bargauge",
     "description": "Datastore utilization (percentage).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((vmware_datastore_capacity_size{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"} - vmware_datastore_freespace_size{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}) / vmware_datastore_capacity_size{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}) * 100",
       "legendFormat": "Datacenter: {{ dc_name }} Datastore: {{ ds_name }}"
      }
     ]
    },
    {
     "title": "Provisioned Datastore space",
     "type": "bargauge",
     "description": "Provisioned Datastore utilization (percentage).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((vmware_datastore_provisoned_size{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}) / vmware_datastore_capacity_size{job=~\"$job\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", ds_cluster=\"\"}) * 100",
       "legendFormat": "Datacenter: {{ dc_name }} Datastore: {{ ds_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk R/W rate",
     "type": "timeseries",
     "description": "Disk Read and Write rate in bytes/sec.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "(vmware_host_disk_read_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=~\"\"} + vmware_host_disk_write_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=~\"\"})",
       "legendFormat": "Disk Read and Write: Datacenter: {{ dc_name }}"
      }
     ]
    },
    {
     "title": "Disk Read rate",
     "type": "timeseries",
     "description": "Disk Read rate in  bytes/sec, thus rate at which data is read from each LUN on the host. \n\nRead rate = # blocksRead per second x blockSize.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "(vmware_host_disk_read_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=~\"\"})",
       "legendFormat": "Disk Read:  Datacenter: {{ dc_name }}"
      }
     ]
    },
    {
     "title": "Disk Write rate",
     "type": "timeseries",
     "description": "Disk Read rate in  bytes/sec, thus average number of kilobytes written to disk each second during the collection interval.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "(vmware_host_disk_write_average{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=~\"\"})",
       "legendFormat": "Disk Write:  Datacenter: {{ dc_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Network utilization",
     "type": "timeseries",
     "description": "Data usage: Network utilization (combined transmit- and receive-rates) during the interval, thus the sum of data transmitted and received across all physical NIC instances connected to the host.\n\nData Rx: Average amount of data received per second.\n\nData Tx: Average amount of data transmitted per second.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_host_net_usage_average{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Data Usage: Datacenter: {{ dc_name }}"
      },
      {
       "expr": "vmware_host_net_bytesRx_average{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Data Rx: Datacenter: {{ dc_name }}"
      },
      {
       "expr": "vmware_host_net_bytesTx_average{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Data Tx: Datacenter: {{ dc_name }}"
      }
     ]
    },
    {
     "title": "Errors and dropped packets",
     "type": "timeseries",
     "description": "Errors Rx: Number of packets with errors received during the sampling interval.\n\nErrors Tx: Number of packets with errors transmitted during the sampling interval.\n\nDropped Rx: Number of received packets dropped during the collection interval.\n\nDropped Tx: Number of transmitted packets dropped during the collection interval.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "vmware_host_net_errorsRx_summation{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Errors Rx: Datacenter: {{ dc_name }}"
      },
      {
       "expr": "vmware_host_net_errorsTx_summation{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Errors Tx: Datacenter: {{ dc_name }}"
      },
      {
       "expr": "vmware_host_net_droppedRx_summation{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Dropped Rx: Datacenter: {{ dc_name }}"
      },
      {
       "expr": "vmware_host_net_droppedTx_summation{job=~\"$job\", dc_name=\"$dc_name\", cluster_name=\"\"}",
       "legendFormat": "Dropped Tx: Datacenter: {{ dc_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redundancy (boolean)",
     "type": "timeseries",
     "description": "VMWare sensor redundancy value (1=ok / 0=ko) labeled by sensor name from the host.\n\nArchitecting for redundancy means that if a VMware ESXi™ Server host fails,\nneighboring hypervisors configured in the same VMware vSphere® cluster (a group of hosts) are able to\ncontinue offering the virtualized layer without adversely impacting the VNFs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "vmware_host_sensor_redundancy{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\", ds_cluster=\"\"}",
       "legendFormat": "Datacenter: {{ dc_name }} {{cluster_name}} Sensor name: {{name}}"
      }
     ]
    }
   ]
  }
 ]
}