{
 "title": "Prometheus Stats",
 "description": "The  official, pre-built Prometheus Stats Dashboard.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": "cn-monitor-1.cn.ece.ntua.gr:9090"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"http://prometheus.io/assets/prometheus_logo_grey.svg\" alt=\"Prometheus logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">Prometheus</span>\n\n<p style=\"margin-top: 10px;\">You're using Prometheus, an open-source systems monitoring and alerting toolkit originally built at SoundCloud. For more information, check out the <a href=\"http://www.grafana.org/\">Grafana</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects.</p>"
   }
  },
  { "title": "Prometheus build info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Prometheus host",
   "type": "stat",
   "description": "Name of prometheus host.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Prometheus service uptime.",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=~\"$node\", job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Go version",
   "type": "stat",
   "description": "Go version.",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$node\"}",
     "legendFormat": "{{goversion}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "stat",
   "description": "Revision.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$node\"}",
     "legendFormat": "{{revision}}"
    }
   ]
  },
  {
   "title": "Branch",
   "type": "stat",
   "description": "Branch.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$node\"}",
     "legendFormat": "Branch: {{branch}}"
    }
   ]
  },
  {
   "title": "Configurations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful configuration reloads",
     "type": "timeseries",
     "description": "Indication whether the last configuration reload attempt was successful.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "prometheus_config_last_reload_successful{instance=\"$node\"}",
       "legendFormat": "Successful reloads:"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time utilization",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[5m])",
       "legendFormat": "Target: {{instance}} Job: {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "options": {
      "content": "#### Scrapes\nPrometheus scrapes metrics from instrumented jobs, either directly or via an intermediary push gateway for short-lived jobs. Target scrapes will show how frequently targets are scraped, as measured over the last 5 minutes, per time series in the range vector. Scrape Duration will show how long the scrapes are taking, with percentiles available as series. "
     }
    },
    {
     "title": "Scrape duration",
     "type": "timeseries",
     "description": "Actual intervals between scrapes.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds{instance=~\"$node\"}[$__interval])",
       "legendFormat": "Duration:"
      }
     ]
    },
    {
     "title": "Intervals between scrapes",
     "type": "timeseries",
     "description": "Actual intervals between scrapes.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds{instance=~\"$node\"}[$__interval])",
       "legendFormat": "Interval:"
      },
      {
       "expr": "rate(prometheus_target_interval_length_seconds_sum[5m])",
       "legendFormat": "Target interval lenght: Interval: {{interval}} "
      },
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
       "legendFormat": "Target interval lenght: Interval: {{interval}} "
      }
     ]
    },
    {
     "title": "Target Scrapes (last 5m)",
     "type": "timeseries",
     "description": "Actual intervals between scrapes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count{instance=~\"$node\"}[5m])",
       "legendFormat": "Prometheus host: {{instance}} Job: {{job}}"
      }
     ]
    },
    {
     "title": "Failed scrape loop reloads",
     "type": "timeseries",
     "description": "Total number of failed scrape loop reloads.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_scrape_pool_reloads_failed_total{instance=~\"$node\"}[$__interval])",
       "legendFormat": "Failed reloads:"
      }
     ]
    },
    {
     "title": "Syncs on scrape",
     "type": "timeseries",
     "description": "Number of syncs executed on a scrape pool.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_scrape_pool_sync_total{instance=~\"$node\"}[$__interval])",
       "legendFormat": "Scrape job: {{scrape_job}}"
      }
     ]
    },
    {
     "title": "Scrape pool creations",
     "type": "timeseries",
     "description": "Failed: Total number of scrape pool creations that failed.\n\nAttempts: Total number of scrape pool creation attempts.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_scrape_pools_failed_total{instance=~\"$node\"}[$__interval])",
       "legendFormat": "Failed: "
      },
      {
       "expr": "rate(prometheus_target_scrape_pools_total[5m])",
       "legendFormat": "Attempts:"
      }
     ]
    },
    {
     "title": "Interval to sync the scrape pool",
     "type": "timeseries",
     "description": "Interval to sync the scrape pool.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_sync_length_seconds_count[5m])",
       "legendFormat": "Scrape job: {{scrape_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries",
     "type": "timeseries",
     "description": "Current queries: The current number of queries being executed or waiting.\n\nMaximum concurrent queries: The max number of concurrent queries.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_engine_queries{instance=~\"$node\"}",
       "legendFormat": "Current queries: "
      },
      {
       "expr": "prometheus_engine_queries_concurrent_max",
       "legendFormat": "Maximum concurrent queries:"
      }
     ]
    },
    {
     "title": "Remote read queries",
     "type": "timeseries",
     "description": "The current number of remote read queries being executed or waiting.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_api_remote_read_queries{instance=~\"$node\"}",
       "legendFormat": "Read queries:"
      }
     ]
    },
    {
     "title": "Prometheus Engine Query Duration",
     "type": "timeseries",
     "description": "Query timings.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds{instance=~\"$node\"}[$__interval])",
       "legendFormat": "Duartion: Slice: {{slice}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert managers discovered and active",
     "type": "stat",
     "description": "Number of alertmanagers discovered and active",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_alertmanagers_discovered{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Alert notification Queue ",
     "type": "timeseries",
     "description": "Capacity size: Capacity of the alert notifications queue.\n\nAlert notifications: The number of alert notifications in the queue.",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_notifications_queue_capacity{instance=~\"$node\"}",
       "legendFormat": "Capacity size: "
      },
      {
       "expr": "prometheus_notifications_queue_length",
       "legendFormat": "Alert notificatons: "
      }
     ]
    },
    {
     "title": "Number of alerts dropped due to errors",
     "type": "timeseries",
     "description": "Total number of alerts dropped due to errors when sending to Alertmanager.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(prometheus_notifications_dropped_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Notifications dropped: "
      }
     ]
    }
   ]
  },
  {
   "title": "Service discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Opened: Total number of connections opened to the listener of a given name.\n\nClosed: Total number of connections closed that were made to the listener of a given name.\n\nFailed: Total number of connections failed to dial by the dialer a given name.\n\nSuccessfully established: otal number of connections successfully established by the given dialer a given name.\n\nAttempted: Total number of connections attempted by the given dialer a given name.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "net_conntrack_listener_conn_accepted_total{instance=~\"$node\"}",
       "legendFormat": "Opened: Listener name: {{listener_name}}"
      },
      {
       "expr": "rate(net_conntrack_listener_conn_closed_total[5m])",
       "legendFormat": "Closed: Listener name: {{listener_name}}"
      },
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total[5m])",
       "legendFormat": "Failed: Dialer name: {{dialer_name}} Reason: {{reason}}"
      },
      {
       "expr": "rate(net_conntrack_dialer_conn_established_total[5m])",
       "legendFormat": "Successfully established: {{dialer_name}}"
      },
      {
       "expr": "rate(net_conntrack_dialer_conn_attempted_total[5m])",
       "legendFormat": "Attempted: Dialer name: {{dialer_name}}"
      }
     ]
    },
    {
     "title": "Discovered targets",
     "type": "timeseries",
     "description": "Current number of discovered targets.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_sd_discovered_targets{instance=~\"$node\"}",
       "legendFormat": "Config: {{config}}  Name: {{name}}"
      }
     ]
    },
    {
     "title": "Failed service discovery configurations",
     "type": "timeseries",
     "description": "Current number of service discovery configurations that failed to load.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "prometheus_sd_failed_configs{instance=~\"$node\"}",
       "legendFormat": "Failed configs: Name: {{name}}"
      }
     ]
    },
    {
     "title": "Update events sent to the SD consumers",
     "type": "timeseries",
     "description": "Total SD updates: Total number of update events sent to the SD consumers.\n\nReceived SD updates: Total number of update events received from the SD providers.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_sd_updates_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total SD updates: Name: {{name}}"
      },
      {
       "expr": "sum(prometheus_sd_received_updates_total) ",
       "legendFormat": "Received SD updates: Name: {{name}}"
      }
     ]
    },
    {
     "title": "Duration of the File-SD scan",
     "type": "timeseries",
     "description": "Scan duration: The duration of the File-SD scan in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_sd_file_scan_duration_seconds[5m])",
       "legendFormat": "Scan duration:"
      }
     ]
    },
    {
     "title": "File-SD read errors",
     "type": "timeseries",
     "description": "File-SD read errors: The number of File-SD read errors.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "rate(prometheus_sd_file_read_errors_total{instance=~\"$node\"}[5m])",
       "legendFormat": "File-SD read errors:"
      }
     ]
    },
    {
     "title": "DNS-SD lookups",
     "type": "timeseries",
     "description": "Total SD DNS lookups: The number of DNS-SD lookups.\n\nTotal SD DNS lookup failures: The number of DNS-SD lookup failures.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_sd_dns_lookups_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total SD DNS lookups: "
      },
      {
       "expr": "rate(prometheus_sd_dns_lookup_failures_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total SD DNS lookup failures: "
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests",
     "type": "timeseries",
     "description": "Counter of HTTP requests.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_requests_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total requests: Code: {{code}} Handler: {{handler}}"
      }
     ]
    },
    {
     "title": "Response size for HTTP requests",
     "type": "timeseries",
     "description": "Response size for HTTP requests.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(prometheus_http_response_size_bytes_bucket[5m])))",
       "legendFormat": "Requests: Handler: {{handler}}"
      }
     ]
    },
    {
     "title": "Latency of HTTP requests",
     "type": "timeseries",
     "description": "Latency of HTTP requests in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(prometheus_http_request_duration_seconds_bucket{instance=~\"$node\"}[5m])) by (le))",
       "legendFormat": "Latency: Handler: {{handler}}"
      },
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum{instance=~\"$node\"}[5m])",
       "legendFormat": "Latency: Handler: {{handler}}"
      },
      {
       "expr": "rate(prometheus_http_request_duration_seconds_count{instance=~\"$node\"}[5m])",
       "legendFormat": "Latency: Handler: {{handler}}"
      }
     ]
    },
    {
     "title": "Total number of scrapes by HTTP status code",
     "type": "timeseries",
     "description": "Total number of scrapes by HTTP status code.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(promhttp_metric_handler_requests_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Code: {{code}}"
      }
     ]
    },
    {
     "title": "Total number of completed pages",
     "type": "timeseries",
     "description": "Total number of completed pages.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_completed_pages_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Prometheus host: {{instance}} Job: {{job}}"
      }
     ]
    },
    {
     "title": "Total number of page flushes",
     "type": "timeseries",
     "description": "Total number of page flushes.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_page_flushes_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Prometheus host: {{instance}} Job: {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual memory size",
     "type": "timeseries",
     "description": "Virtual memory size in bytes.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=~\"$node\"}",
       "legendFormat": "Target: {{instance}} Job: {{job}}"
      }
     ]
    },
    {
     "title": "Resident memory size",
     "type": "timeseries",
     "description": "Resident memory size in bytes.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$node\"}",
       "legendFormat": "Target: {{instance}} Job: {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rule evaluatons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rule group evaluations",
     "type": "timeseries",
     "description": "Total group evaluations: The total number of scheduled rule group evaluations, whether executed or missed.\n\nMissed group evaluations: The total number of rule group evaluations missed due to slow rule group evaluation.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_iterations_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total group evaluations:"
      },
      {
       "expr": "rate(prometheus_rule_group_iterations_missed_total[5m])",
       "legendFormat": "Missed group evaluations: "
      }
     ]
    },
    {
     "title": "Rule evaluations",
     "type": "timeseries",
     "description": "Total evaluations: The total number of rule evaluations.\n\nFailed evaluations: The total number of rule evaluation failures.\n\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(prometheus_rule_evaluations_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total evaluations:"
      },
      {
       "expr": "rate(prometheus_rule_evaluation_failures_total[5m])",
       "legendFormat": "Failed evaluations:"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time taken to recompact blocks to remove tombstones",
     "type": "timeseries",
     "description": "The time taken to recompact blocks to remove tombstones.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(prometheus_tsdb_tombstone_cleanup_seconds_bucket{instance=~\"$node\"}[5m])) by (le))",
       "legendFormat": "Duration:"
      }
     ]
    },
    {
     "title": "Storage block bytes",
     "type": "timeseries",
     "description": "The number of bytes that are currently used for local storage by all blocks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_storage_blocks_bytes",
       "legendFormat": "Storage block bytes:"
      }
     ]
    },
    {
     "title": "Database data",
     "type": "timeseries",
     "description": "Reloads: Number of times the database reloaded block data from disk.\n\nFailures: Number of times the database failed to reload block data from disk.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      { "expr": "prometheus_tsdb_reloads_total", "legendFormat": "Reloads:" },
      {
       "expr": "prometheus_tsdb_reloads_failures_total",
       "legendFormat": "Failures: "
      }
     ]
    },
    {
     "title": "Size of symbol table on disk",
     "type": "timeseries",
     "description": "Size of symbol table on disk (in bytes).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_symbol_table_size_bytes",
       "legendFormat": "Total size"
      }
     ]
    },
    {
     "title": "Head chunks",
     "type": "timeseries",
     "description": "Head chunks: Total number of chunks in the head block.\n\nCreated chunks: Total number of chunks created in the head.\n\nRemoved chunks: Total number of chunks removed in the head.\n\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{instance=~\"$node\"}",
       "legendFormat": "Head chunks: "
      },
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Created chunks:"
      },
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Removed chunks: "
      }
     ]
    },
    {
     "title": "Total series in the head block",
     "type": "timeseries",
     "description": "Head series: Total number of series in the head block.\n\nCreated head series: Total number of series created in the head.\n\nRemoved head series: Total number of series removed in the head.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{instance=~\"$node\"}",
       "legendFormat": "Head series:"
      },
      {
       "expr": "prometheus_tsdb_head_series_created_total",
       "legendFormat": "Created head series: "
      },
      {
       "expr": "prometheus_tsdb_head_series_removed_total",
       "legendFormat": "Removed head series: "
      }
     ]
    },
    {
     "title": "Attempted checkpoint deletions",
     "type": "timeseries",
     "description": "Total checkpoint deletions: Total number of checkpoint deletions attempted.\n\nFailed checkpoint deletions: Total number of checkpoint deletions that failed.\n\nFailed checkpoint creations: Total number of checkpoint creations that failed.\n\nAttempted checkpoint creatins: Total number of checkpoint creations attempted.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_checkpoint_deletions_total{instance=~\"$node\"}",
       "legendFormat": "Total chekpoint deletions: "
      },
      {
       "expr": "prometheus_tsdb_checkpoint_deletions_failed_total",
       "legendFormat": "Failed checkpoint deletions:"
      },
      {
       "expr": "rate(prometheus_tsdb_checkpoint_creations_failed_total[5m])",
       "legendFormat": "Failed checkpoint creations: "
      },
      {
       "expr": "prometheus_tsdb_checkpoint_creations_total",
       "legendFormat": "Attempted checkpoint creations"
      }
     ]
    },
    {
     "title": "Loaded data blocks",
     "type": "timeseries",
     "description": "Number of currently loaded data blocks.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{instance=~\"$node\"}",
       "legendFormat": "Loaded blocks:"
      }
     ]
    },
    {
     "title": "Compactions",
     "type": "timeseries",
     "description": "Total compactions triggered: Total number of triggered compactions for the partition.\n\nTotal executed compactions: Total number of compactions that were executed for the partition.\n\nTotal failed compactions: Total number of compactions that failed for the partition.\n\nCompactions on overlapping blocks:: Total number of compactions done on overlapping blocks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compactions_triggered_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total compactions triggered:"
      },
      {
       "expr": "rate(prometheus_tsdb_compactions_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total executed compactions:"
      },
      {
       "expr": "rate(prometheus_tsdb_compactions_failed_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total failed compactions: "
      },
      {
       "expr": "rate(prometheus_tsdb_vertical_compactions_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Compactions on overlapping blocks:"
      }
     ]
    },
    {
     "title": "Duration of compaction runs",
     "type": "timeseries",
     "description": "Duration of compaction runs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{instance=~\"$node\"}[5m])",
       "legendFormat": "Duration: "
      }
     ]
    },
    {
     "title": "Chunks on their first compaction",
     "type": "timeseries",
     "description": "Final size of chunks on their first compaction.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(prometheus_tsdb_compaction_chunk_size_bytes_bucket{instance=~\"$node\"}[5m])) by (le))",
       "legendFormat": "Chunk size:"
      }
     ]
    },
    {
     "title": "Samples on their first compaction",
     "type": "timeseries",
     "description": "Samples on their first compaction.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(prometheus_tsdb_compaction_chunk_samples_bucket{instance=~\"$node\"}[5m])) by (le))",
       "legendFormat": "Chunk samples bucket:"
      },
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{instance=~\"$node\"}[5m])",
       "legendFormat": "Chunk samples sum: "
      },
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_samples_count{instance=~\"$node\"}[5m])",
       "legendFormat": "Chunk samples count:"
      }
     ]
    },
    {
     "title": "Appender transactions",
     "type": "timeseries",
     "description": "Number of currently active appender transactions.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders{instance=~\"$node\"}",
       "legendFormat": "Transactions:"
      }
     ]
    },
    {
     "title": "Head truncations",
     "type": "timeseries",
     "description": "Total attempted truncations: Total number of head truncations attempted.\n\nFailed truncations: Total number of head truncations that failed.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_truncations_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total attempted truncations: "
      },
      {
       "expr": "rate(prometheus_tsdb_head_truncations_failed_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Failed truncations: "
      }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of open File Descriptors",
     "type": "timeseries",
     "description": "Maximum open file descriptors: Maximum number of open file descriptors.\n\nOpen file descriptors: Number of open file descriptors.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_max_fds{instance=~\"$node\"}",
       "legendFormat": "Maximum open file descriptors: Target: {{instance}} Job: {{job}}"
      },
      {
       "expr": "process_open_fds",
       "legendFormat": "Open file descriptors: Target: {{instance}} Job:{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Template Text",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Template text expansions",
     "type": "timeseries",
     "description": "Total expansions: The total number of template text expansions.\n\nFailed expansions: The total number of template text expansion failures.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(prometheus_template_text_expansions_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Total expansions: "
      },
      {
       "expr": "rate(prometheus_template_text_expansion_failures_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Failed expansions: "
      }
     ]
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current watcher goroutines",
     "type": "timeseries",
     "description": "The current number of watcher goroutines.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "prometheus_treecache_watcher_goroutines{instance=~\"$node\"}",
       "legendFormat": "Goroutines: "
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZooKeeper failures",
     "type": "timeseries",
     "description": "The total number of ZooKeeper failures.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(prometheus_treecache_zookeeper_failures_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Zookeeper Failures:"
      }
     ]
    }
   ]
  }
 ]
}