{
 "title": "VM Stats",
 "description": "VMware ESXi single instance graphs.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "vmware_vcenter,vmware_vcenter2" },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(vmware_vm_power_state, vm_name)"
    }
   },
   { "name": "dc_name", "label": "dc_name", "query": { "query": "label_values(dc_name)" } },
   { "name": "datastore", "label": "ds_name", "query": { "query": "label_values(ds_name)" } }
  ]
 },
 "panels": [
  { "title": "High level stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host name",
   "type": "stat",
   "description": "Name of Host.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_hardware_info{job=~\"$job\"} ",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Host uptime",
   "type": "stat",
   "description": "Uptime of Host.",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(vmware_host_boot_timestamp_seconds{job=~\"$job\", dc_name=~\"$dc_name\", cluster_name=\"\"})"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "description": "Total count of Virtual Machines, regardless of power state.",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Powered on VMs",
   "type": "stat",
   "description": "Count of Virtual Machines that are currently powered on.",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{job=~\"$job\"} > 0)"
    }
   ]
  },
  {
   "title": "Powered off VMs",
   "type": "stat",
   "description": "Count of Virtual Machines that are currently powered off.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{job=~\"$job\"}) - count(vmware_vm_power_state{job=~\"$job\"} == 1)"
    }
   ]
  },
  {
   "title": "Powered on VMs",
   "type": "stat",
   "description": "Names of powered on VMs.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
     "legendFormat": "VM: {{vm_name}} Datacenter: {{dc_name}} Datastore: {{ds_name}}"
    }
   ]
  },
  {
   "title": "Average VM uptime",
   "type": "stat",
   "description": "Average uptime (time powered on) of each Virtual Machine.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(vmware_vm_boot_timestamp_seconds{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\"})",
     "legendFormat": "VM: {{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "VCPUs per VM",
     "type": "bargauge",
     "description": "Number of Virtual CPUs assigned to each VM.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_vm_num_cpu{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "VM CPU Usage",
     "type": "timeseries",
     "description": "Usage: Amount of actively used virtual CPU, as a percentage of total available CPU. This is the host's view of the CPU usage, not the guest operating system view. It is the average CPU utilization over all available virtual CPUs in the virtual machine. For example, if a virtual machine with one virtual CPU is running on a host that has four physical CPUs and the CPU usage is 100%, the virtual machine is using one physical CPU completely.\n\nDemand: The amount of CPU resources a virtual machine would use if there were no CPU contention or CPU limit.\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vmware_vm_cpu_usage_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}/vmware_vm_max_cpu_usage{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}*100",
       "legendFormat": "CPU Usage: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_cpu_demand_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}/vmware_vm_max_cpu_usage{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}*100",
       "legendFormat": "CPU Demand: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "VM CPU usage (MHz)",
     "type": "timeseries",
     "description": "Usage: Amount of actively used virtual CPU. This is the host's view of the CPU usage, not the guest operating system view.\n\nDemand: The amount of CPU resources a virtual machine would use if there were no CPU contention or CPU limit.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "(vmware_vm_cpu_usagemhz_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"})*1000000",
       "legendFormat": "CPU Usage: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "(vmware_vm_cpu_demand_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"})*1000000",
       "legendFormat": "CPU Demand: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "VM CPU time utilization",
     "type": "timeseries",
     "description": "Ready: Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval. CPU ready time is dependent on the number of virtual machines on the host and their CPU loads.\n\nCo-Stop: Time the virtual machine is ready to run, but is unable to run due to co-scheduling constraints\n\nIdle: Total time that the CPU spent in an idle state\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vmware_vm_cpu_ready_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Cpu Ready: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_cpu_costop_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Co-Stop:  VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_cpu_idle_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Idle: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "CPU max limited ",
     "type": "timeseries",
     "description": "Time the virtual machine is ready to run, but is not running because it has reached its maximum CPU limit setting.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vmware_vm_cpu_maxlimited_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Max limited: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM memory Capacity",
     "type": "barchart",
     "description": "VM maximum memory availability in Megabytes.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "vmware_vm_memory_max{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}"
      }
     ]
    },
    {
     "title": "VM average memory usage",
     "type": "timeseries",
     "description": "Memory usage as percentage of total configured or available memory.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(vmware_vm_mem_usage_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}) / vmware_vm_memory_max{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"} *100",
       "legendFormat": "Usage: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "VM active and consumed memory usage (GB)",
     "type": "timeseries",
     "description": "Active:  Amount of guest “physical” memory actively used.\n\nConsumed: Amount of guest physical memory consumed by the virtual machine for guest memory. Consumed memory does not include overhead memory. It includes shared memory and memory that might be reserved, but not actually used. Use this metric for charge-back purposes.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "vmware_vm_mem_active_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Active: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_mem_consumed_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Consumed:  VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "VM memory swapped",
     "type": "timeseries",
     "description": "Swapped: Current amount of guest physical memory swapped out to the virtual machine swap file by the VMkernel. Swapped memory stays on disk until the virtual machine needs it. This statistic refers to VMkernel swapping and not to guest OS swapping.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_vm_mem_swapped_average{job=~\"$job\", vm_name=~\"$vm\"}",
       "legendFormat": "Swapped: datacenter: {{ dc_name }} vm: {{ cluster_name }} {{ vm_name }}"
      }
     ]
    },
    {
     "title": "VM Ballooning",
     "type": "timeseries",
     "description": "Balloning: Amount of memory allocated by the virtual machine memory control driver (vmmemctl), which is installed with VMware Tools. It is a VMware exclusive memory-management driver that controls ballooning. It is the amount of guest physical memory that is currently reclaimed from the virtual machine through ballooning. This is the amount of guest physical memory that has been allocated and pinned by the balloon driver.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_vm_mem_vmmemctl_average{job=~\"$job\", vm_name=~\"$vm\"}",
       "legendFormat": "Ballooning: Vm: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Network utilization",
     "type": "timeseries",
     "description": "Received: average rate at which data was received during the interval. This represents the bandwidth of the network.\n\nTransmitted: Average rate at which data was transmitted during the interval. This represents the bandwidth of the network.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_vm_net_received_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}+ vmware_vm_net_transmitted_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Total Usage: Vm: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_net_received_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Received: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_net_transmitted_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Transmitted: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Broadcast and multicast packets",
     "type": "timeseries",
     "description": "Broadcast Rx: Number of broadcast packets received during the sampling interval.\n\nBroadcast Tx: Number of broadcast packets transmitted during the sampling interval.\n\nMulticast Rx: Number of multicast packets received during the sampling interval.\n\nMulticast Tx: Number of multicast packets transmitted during the sampling interval.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmware_vm_net_broadcastTx_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Broadcast Tx packets: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_net_broadcastRx_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Broadcast Rx packets: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_net_multicastTx_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Multicast Tx packets: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_net_multicastRx_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Multicast Rx packets: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "VM dropped network packets",
     "type": "timeseries",
     "description": "Dropped Rx packets: Number of received packets dropped during the collection interval.\nDropped Tx packets: Number of transmitted packets dropped during the collection interval.\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmware_vm_net_droppedRx_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Dropped Rx packets: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_net_droppedTx_summation{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Dropped Tx packets: VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk capacity per partition",
     "type": "timeseries",
     "description": "Disk capacity per partition.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmware_vm_guest_disk_capacity{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Capacity:  VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }} Partition: {{partition}}"
      }
     ]
    },
    {
     "title": "Free Disk space per partition",
     "type": "timeseries",
     "description": "Free Disk space per partition.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmware_vm_guest_disk_free{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Free capacity: Vm: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}  Partition: {{partition}}"
      }
     ]
    },
    {
     "title": "VM Disk Read And Write",
     "type": "timeseries",
     "description": "Number of read and write kilobytes from the disk each second during the collection interval.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "vmware_vm_disk_read_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"} + vmware_vm_disk_write_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Total Usage: Vm: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      },
      {
       "expr": "vmware_vm_disk_read_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Read Usage: datacenter: {{ dc_name }} vm: {{ cluster_name }} {{ vm_name }}"
      },
      {
       "expr": "vmware_vm_disk_write_average{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Write Usage: datacenter: {{ dc_name }} vm: {{ cluster_name }} {{ vm_name }}"
      }
     ]
    },
    {
     "title": "Maximum VM disk latency",
     "type": "timeseries",
     "description": "Latency: Highest latency value across all disks used by the host. Latency measures the time taken to process a SCSI command issued by the guest OS to the virtual machine. The kernel latency is the time VMkernel takes to process an IO request. The device latency is the time it takes the hardware to handle the request.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vmware_vm_disk_maxTotalLatency_latest{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "Disk Latency: Vm: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "VM tools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM tools version",
     "type": "timeseries",
     "description": "VM tools version.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmware_vm_guest_tools_version{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}Tools version: {{tools_version}}"
      }
     ]
    },
    {
     "title": "VM tools version status",
     "type": "timeseries",
     "description": "VM tools version status.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "vmware_vm_guest_tools_version_status{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}Tools version status: {{tools_version_status}}"
      }
     ]
    },
    {
     "title": "VM tools running status",
     "type": "timeseries",
     "description": "VM tools running status.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "vmware_vm_guest_tools_running_status{job=~\"$job\", vm_name=~\"$vm\", dc_name=\"$dc_name\", ds_name=~\"$datastore\", cluster_name=\"\"}",
       "legendFormat": "VM: {{vm_name}} Datacenter: {{ dc_name }} Datastore: {{ds_name}} {{ cluster_name }}Tools status: {{tools_status}}"
      }
     ]
    }
   ]
  }
 ]
}