# This file is located at the path /etc/prometheus
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['cn-monitor-1.cn.ece.ntua.gr:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - prometheus_rules.yml
  - node_exporter_rules.yml
  - blackbox_rules.yml
  - vmware_rules.yml
  - alertmanager_rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
#  # The job name is added as a label job=<job_name> to any timeseries scraped from this config.
- job_name: 'prometheus'
  static_configs:
  - targets: ['cn-monitor-1.cn.ece.ntua.gr:9090']

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.

#static_configs:
- job_name: 'node-exporter'
  static_configs:
          - targets: ['cn-monitor-1.cn.ece.ntua.gr:9100', 'ladon.telecom.ece.ntua.gr:9100', 'ulairi.telecom.ece.ntua.gr:9100', 'cn-monitor-2.cn.ece.ntua.gr:9100', 'courses.cn.ece.ntua.gr:9100', 'bbb.cn.ntua.gr:9100', 'bbb2.cn.ntua.gr:9100', 'gitlab.telecom.ece.ntua.gr:9100', 'bench-moodle-1:9100', 'onos.telecom.ece.ntua.gr:9100']
- job_name: 'alertmanager'
  static_configs:
          - targets: ['cn-monitor-1.cn.ece.ntua.gr:9093']
- job_name: 'gitlab_exporter_metrics'
  metrics_path: "/metrics"
  static_configs:
    - targets:
      - gitlab.telecom.ece.ntua.gr:9168
# Monitoring Big Blue Button
- job_name: 'bbb'
  scrape_interval: 5s
  static_configs:
  - targets: ['bbb2.cn.ntua.gr:9688', 'bbb.cn.ntua.gr:9688']
# Monitoring Vmware (Esx, Vcenter etc.)
- job_name: 'vmware_vcenter'
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'atlas.telecom.ece.ntua.gr'
  params:
    section: [atlas]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 147.102.40.79:9272
# Monitoring Vmware(2) (Esx, Vcenter etc.)
- job_name: 'vmware_vcenter2'
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'uranos.cn.ntua.gr'
  params:
    section: [uranos]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 147.102.40.79:9272
#Monitoring HTTP(S) Servers
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - https://courses.cn.ntua.gr   # Target no.1
      - https://www.cn.ntua.gr       # Target no.2
      - https://students.ece.ntua.gr # Target no.3
      - https://helios.ntua.gr       # Target no.4
      - https://www.ece.ntua.gr      # Target no.5
      - http://users.ntua.gr         # Target no.6 
      - https://bbb2.cn.ntua.gr      # Target no.7 
      - https://bbb.cn.ntua.gr       # Target no.8
      - http://onos.telecom.ece.ntua.gr # Target no.9
      - https://cn-monitor-1.cn.ece.ntua.gr:3000 # Target no.10
      - http://cn-monitor-1.cn.ece.ntua.gr:9090 # Target no.11
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: cn-monitor-2.cn.ntua.gr:9115  # The blackbox exporter's real hostname:port.
# Monitoring SNMP devices
# - job_name: 'snmp'
#  static_configs:
#    - targets:
#      -  alderaan.cn.ece.ntua.gr
# SNMP device.
#      - switch.local # SNMP device.
#  metrics_path: /metrics
#  params:
#    module: [if_mib]
#  relabel_configs:
#    - source_labels: [__address__]
#      target_label: __param_target
#    - source_labels: [__param_target]
#      target_label: instance
#    - target_label: __address__
#      replacement: cn-monitor-2.cn.ece.ntua.gr:9116  #  The SNMP exporter's real hostname:port.
#  scrape_interval: 10s